name: ZAP DAST Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Build and run
        run: |
          docker build -t isen-python .
          docker run -d --name app -p 8080:8080 isen-python
          sleep 25  # Délai augmenté pour les apps lentes

      - name: Verify app
        run: |
          docker ps -a
          curl -v http://localhost:8080 || docker logs app

      - name: ZAP Scan with resource limits
        run: |
          docker run --rm \
            --memory="2g" \
            --cpus="1.5" \
            -v $(pwd):/zap/wrk/:rw \
            -e ZAP_AUTH_HEADER="X-API-KEY" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:8080 \
            -m 1 -j -l PASS -a

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: zap-report.json
        if: always()