name: ZAP DAST Scan
on:
  push:
    branches: [main]
  pull_request:

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Build and run app
        run: |
          docker build -t isen-python .
          docker run -d --name app -p 8080:8080 isen-python
          sleep 30  # Délai généreux

      - name: Verify app
        run: |
          curl -sSf http://localhost:8080 || docker logs app

      - name: Run ZAP Scan (with error handling)
        run: |
          set +e  # Désactive l'arrêt sur erreur
          docker run --rm \
            --network host \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:8080 \
            -m 1 -j -l PASS -a \
            -J zap-report.json 2>&1 | tee zap.log
          echo "ZAP exit code: $?"  # Affiche le code de sortie

      - name: Force report creation if missing
        if: always()
        run: |
          [ -f zap-report.json ] || echo '{"@version":"1.0.0","site":[]}' > zap-report.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: |
            zap-report.json
            zap.log
        if: always()