name: ZAP DAST Scan
on: [push, pull_request]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    continue-on-error: true 

    steps:
      - uses: actions/checkout@v4

      - name: Build and run app
        run: |
          docker build -t isen-python .
          docker run -d --name app -p 8080:8080 isen-python
          sleep 25  # Délai adapté aux apps lentes

      - name: Pre-scan debug
        run: |
          echo "=== Conteneurs en cours ==="
          docker ps -a
          echo "=== Logs de l'application ==="
          docker logs app || true
          echo "=== Accès à l'application ==="
          curl -v http://localhost:8080 || true
          echo "=== Fichiers dans /app ==="
          docker exec app ls -la /app || true

      - name: Run ZAP Scan
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \  # Utilise les permissions de l'hôte
            -v $(pwd):/zap/wrk/:rw \
            -e ZAP_JVM_ARGS="-DZAP.permissions.all=true" \  # Force les permissions
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:8080 \
            -m 2 -j -l PASS \
            -J /zap/wrk/zap-report.json

      - name: Post-scan debug
        if: failure()  # Ne s'exécute QUE si le scan échoue
        run: |
          echo "=== Fichiers générés par ZAP ==="
          ls -la | grep -E 'zap|report'
          echo "=== Logs ZAP (si existants) ==="
          cat zap.log || echo "Aucun log ZAP trouvé"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: |
            zap-report.json
            report.xml
            zap.log
        if: always()  # Upload même en cas d'échec